# Copyright 2025 DARWIN EU
# SPDX-License-Identifier: Apache-2.0

"""
CDMConnector: Connect to an OMOP Common Data Model (Python with Ibis).

Lazy-by-default: transformations return Ibis expressions; use collect() or compute()
to materialize. Port of R CDMConnector + omopgenerics.
"""

from cdmconnector.cdm import (
    Cdm,
    cdm_classes,
    cdm_con,
    cdm_disconnect,
    cdm_from_con,
    cdm_from_tables,
    cdm_select,
    cdm_table_from_source,
    cdm_write_schema,
    collect,
    compute,
    copy_cdm_to,
    drop_source_table,
    drop_table,
    empty_achilles_table,
    empty_cdm_reference,
    empty_cohort_table,
    empty_omop_table,
    insert_cdm_to,
    insert_from_source,
    insert_table,
    list_source_tables,
    new_cdm_reference,
    new_cdm_source,
    new_local_source,
    read_source_table,
)
from cdmconnector.cdm import (
    list_tables as cdm_tables,
)
from cdmconnector.characteristics import (
    SummarisedResult,
    bind_summarised_results,
    empty_summarised_result,
    estimate_type_choices,
    new_summarised_result,
    result_columns,
    result_package_version,
    summarise_characteristics,
    summarise_cohort_attrition,
    summarise_cohort_count,
    summarise_cohort_overlap,
    summarise_cohort_timing,
    summarise_large_scale_characteristics,
    table_characteristics,
    table_cohort_attrition,
    table_cohort_count,
    table_cohort_overlap,
    table_cohort_timing,
    table_large_scale_characteristics,
    transform_to_summarised_result,
)
from cdmconnector.codelist import (
    Codelist,
    CodelistWithDetails,
    ConceptSetExpression,
    empty_codelist,
    empty_codelist_with_details,
    empty_concept_set_expression,
    new_codelist,
    new_codelist_with_details,
    new_concept_set_expression,
)
from cdmconnector.cohorts import (
    attrition,
    bind,
    cohort_codelist,
    cohort_count,
    generate_cohort_set,
    generate_concept_cohort_set,
    get_cohort_id,
    get_cohort_name,
    new_cohort_table,
    record_cohort_attrition,
    settings,
)
from cdmconnector.eunomia import (
    download_eunomia_data,
    eunomia_dir,
    eunomia_is_available,
    example_datasets,
    require_eunomia,
)
from cdmconnector.exceptions import (
    CDMConnectorError,
    CDMValidationError,
    CohortError,
    EunomiaError,
    SourceError,
    TableNotFoundError,
)
from cdmconnector.indexes import (
    create_indexes,
    create_table_index,
    existing_indexes,
    expected_indexes,
    status_indexes,
)
from cdmconnector.io import (
    export_codelist,
    export_concept_set_expression,
    export_summarised_result,
    import_codelist,
    import_concept_set_expression,
    import_summarised_result,
)
from cdmconnector.logging_config import (
    create_log_file,
    log_message,
    summarise_log_file,
)
from cdmconnector.patient_profiles import (
    add_age,
    add_categories,
    add_cdm_name,
    add_cohort_intersect_count,
    add_cohort_intersect_date,
    add_cohort_intersect_days,
    add_cohort_intersect_field,
    add_cohort_intersect_flag,
    add_cohort_name,
    add_concept_intersect_count,
    add_concept_intersect_date,
    add_concept_intersect_days,
    add_concept_intersect_field,
    add_concept_intersect_flag,
    add_concept_name,
    add_date_of_birth,
    add_death_date,
    add_death_days,
    add_death_flag,
    add_demographics,
    add_future_observation,
    add_in_observation,
    add_observation_period_id,
    add_prior_observation,
    add_sex,
    add_table_intersect_count,
    add_table_intersect_date,
    add_table_intersect_days,
    add_table_intersect_field,
    add_table_intersect_flag,
    available_estimates,
    end_date_column,
    filter_cohort_id,
    filter_in_observation,
    mock_patient_profiles,
    source_concept_id_column,
    standard_concept_id_column,
    start_date_column,
    summarise_result,
    variable_types,
)
from cdmconnector.plots import (
    plot_characteristics,
    plot_cohort_attrition,
    plot_cohort_count,
    plot_cohort_overlap,
    plot_cohort_timing,
    plot_compared_large_scale_characteristics,
    plot_large_scale_characteristics,
)
from cdmconnector.results import Result
from cdmconnector.schemas import (
    achilles_columns,
    achilles_tables,
    cohort_columns,
    cohort_tables,
    omop_columns,
    omop_data_folder,
    omop_table_fields,
    omop_tables,
)
from cdmconnector.utils import (
    assert_character,
    assert_choice,
    assert_class,
    assert_date,
    assert_list,
    assert_logical,
    assert_numeric,
    assert_table,
    assert_true,
    get_person_identifier,
    is_table_empty,
    number_records,
    number_subjects,
    tmp_prefix,
    to_snake_case,
    unique_id,
    unique_table_name,
)
from cdmconnector.validation import (
    validate_achilles_table,
    validate_age_group_argument,
    validate_cdm_argument,
    validate_cdm_structure,
    validate_cdm_table,
    validate_cohort_argument,
    validate_cohort_id_argument,
    validate_column,
    validate_concept_set_argument,
    validate_name_argument,
    validate_name_level,
    validate_name_style,
    validate_new_column,
    validate_omop_table,
    validate_result_argument,
    validate_strata_argument,
    validate_window_argument,
)
from cdmconnector.vis import (
    bar_plot,
    box_plot,
    customise_text,
    default_table_options,
    empty_plot,
    empty_table,
    format_estimate_name,
    format_estimate_value,
    format_header,
    format_min_cell_count,
    format_table,
    mock_summarised_result,
    plot_columns,
    plot_type,
    scatter_plot,
    table_columns,
    table_options,
    table_style,
    table_type,
    tidy_summarised_result,
    vis_omop_table,
    vis_table,
)
from cdmconnector.vocabulary import search_vocab

__all__ = [
    # Core CDM
    "Cdm",
    "Result",
    "cdm_classes",
    "cdm_con",
    "cdm_disconnect",
    "cdm_from_con",
    "cdm_from_tables",
    "cdm_select",
    "cdm_table_from_source",
    "cdm_tables",
    "cdm_write_schema",
    "collect",
    "compute",
    "copy_cdm_to",
    "drop_source_table",
    "drop_table",
    "insert_cdm_to",
    "insert_from_source",
    "insert_table",
    "list_source_tables",
    "new_cdm_reference",
    "new_cdm_source",
    "new_local_source",
    "read_source_table",
    # Empty creators
    "empty_achilles_table",
    "empty_cdm_reference",
    "empty_cohort_table",
    "empty_omop_table",
    # Codelist classes
    "Codelist",
    "CodelistWithDetails",
    "ConceptSetExpression",
    "new_codelist",
    "new_codelist_with_details",
    "new_concept_set_expression",
    "empty_codelist",
    "empty_codelist_with_details",
    "empty_concept_set_expression",
    # SummarisedResult
    "SummarisedResult",
    "bind_summarised_results",
    "empty_summarised_result",
    "estimate_type_choices",
    "new_summarised_result",
    "result_columns",
    "result_package_version",
    "transform_to_summarised_result",
    "summarise_characteristics",
    "summarise_cohort_attrition",
    "summarise_cohort_count",
    "summarise_cohort_overlap",
    "summarise_cohort_timing",
    "summarise_large_scale_characteristics",
    "table_characteristics",
    "table_cohort_attrition",
    "table_cohort_count",
    "table_cohort_overlap",
    "table_cohort_timing",
    "table_large_scale_characteristics",
    # Plot functions
    "plot_characteristics",
    "plot_cohort_attrition",
    "plot_cohort_count",
    "plot_cohort_overlap",
    "plot_cohort_timing",
    "plot_compared_large_scale_characteristics",
    "plot_large_scale_characteristics",
    # Cohort operations
    "attrition",
    "bind",
    "cohort_codelist",
    "cohort_count",
    "generate_cohort_set",
    "generate_concept_cohort_set",
    "get_cohort_id",
    "get_cohort_name",
    "new_cohort_table",
    "record_cohort_attrition",
    "settings",
    # Import/Export
    "export_codelist",
    "export_concept_set_expression",
    "export_summarised_result",
    "import_codelist",
    "import_concept_set_expression",
    "import_summarised_result",
    # Schema metadata
    "achilles_columns",
    "achilles_tables",
    "cohort_columns",
    "cohort_tables",
    "omop_columns",
    "omop_data_folder",
    "omop_table_fields",
    "omop_tables",
    # Index operations
    "create_indexes",
    "create_table_index",
    "existing_indexes",
    "expected_indexes",
    "status_indexes",
    # Patient profiles - Demographics
    "add_age",
    "add_categories",
    "add_cdm_name",
    "add_cohort_name",
    "add_concept_name",
    "add_date_of_birth",
    "add_demographics",
    "add_future_observation",
    "add_in_observation",
    "add_observation_period_id",
    "add_prior_observation",
    "add_sex",
    # Patient profiles - Death
    "add_death_date",
    "add_death_days",
    "add_death_flag",
    # Patient profiles - Table intersect
    "add_table_intersect_count",
    "add_table_intersect_date",
    "add_table_intersect_days",
    "add_table_intersect_field",
    "add_table_intersect_flag",
    # Patient profiles - Cohort intersect
    "add_cohort_intersect_count",
    "add_cohort_intersect_date",
    "add_cohort_intersect_days",
    "add_cohort_intersect_field",
    "add_cohort_intersect_flag",
    # Patient profiles - Concept intersect
    "add_concept_intersect_count",
    "add_concept_intersect_date",
    "add_concept_intersect_days",
    "add_concept_intersect_field",
    "add_concept_intersect_flag",
    # Patient profiles - Utilities
    "available_estimates",
    "end_date_column",
    "filter_cohort_id",
    "filter_in_observation",
    "mock_patient_profiles",
    "source_concept_id_column",
    "standard_concept_id_column",
    "start_date_column",
    "summarise_result",
    "variable_types",
    # Eunomia
    "download_eunomia_data",
    "eunomia_dir",
    "eunomia_is_available",
    "example_datasets",
    "require_eunomia",
    # Vocabulary
    "search_vocab",
    # Utilities
    "assert_character",
    "assert_choice",
    "assert_class",
    "assert_date",
    "assert_list",
    "assert_logical",
    "assert_numeric",
    "assert_table",
    "assert_true",
    "get_person_identifier",
    "is_table_empty",
    "number_records",
    "number_subjects",
    "tmp_prefix",
    "to_snake_case",
    "unique_id",
    "unique_table_name",
    # Validation
    "validate_achilles_table",
    "validate_age_group_argument",
    "validate_cdm_argument",
    "validate_cdm_structure",
    "validate_cdm_table",
    "validate_cohort_argument",
    "validate_cohort_id_argument",
    "validate_column",
    "validate_concept_set_argument",
    "validate_name_argument",
    "validate_name_level",
    "validate_name_style",
    "validate_new_column",
    "validate_omop_table",
    "validate_result_argument",
    "validate_strata_argument",
    "validate_window_argument",
    # Logging
    "create_log_file",
    "log_message",
    "summarise_log_file",
    # Exceptions
    "CDMConnectorError",
    "CDMValidationError",
    "CohortError",
    "EunomiaError",
    "SourceError",
    "TableNotFoundError",
    # Visualization - Tables
    "default_table_options",
    "empty_table",
    "format_estimate_name",
    "format_estimate_value",
    "format_header",
    "format_min_cell_count",
    "format_table",
    "mock_summarised_result",
    "table_columns",
    "table_options",
    "table_style",
    "table_type",
    "tidy_summarised_result",
    "vis_omop_table",
    "vis_table",
    # Visualization - Plots
    "bar_plot",
    "box_plot",
    "customise_text",
    "empty_plot",
    "plot_columns",
    "plot_type",
    "scatter_plot",
]

__version__ = "0.1.0"
